export const conductores =[
    {
        id: 1,
        nombre: "Juan Carlos González",
        placa : "TZX-123",
        numero:  "(312)-345-6789",
        urlImagen:"",
        cantidad: 1,
    },
    {
        id: 2,
        nombre: "María Fernanda Pérez",
        placa : "XYZ-456",
        numero:  "315 678 1234",
        urlImagen:"",
        cantidad: 1,
    },
    {
        id: 3,
        nombre: "Luis Alberto Ramírez",
        placa : "ABC-789",
        numero:  "310 987 6543",
        urlImagen:"",
        cantidad: 1,
    },
    {
        id: 4,
        nombre: "Ana Lucía Torres",
        placa : " DEF-321",
        numero:  "317 654 3210",
        urlImagen:"",
        cantidad: 1,
    },
    {
        id: 5,
        nombre: "Carlos Andrés Martínez",
        placa : "GHI-654",
        numero:  "319 123 4567",
        urlImagen:"",
        cantidad: 1,
    },
    {
        id: 6,
        nombre: "Diana Marcela López",
        placa : "JKL-987",
        numero:  "311 234 5678",
        urlImagen:"",
        cantidad: 1,
    },
]